### ISSUE TITLE
Loading recent questions into an exam scrolling problem

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#217]
On putting recent questions into an exam the list of recent questions jumps to the top when you try to scroll down the list.

**Comment by christianp** [comment]
Can't reproduce this any more - maybe it was fixed in knockout.js. Do you still have this behaviour? It should happen every 5 seconds, when the list of recent questions is refreshed.

**Comment by christianp** [comment]
Apparently still a problem, but we've only seen it on Bill's computer.

**Comment by christianp** [comment]
Relatedly, each time the list refreshes MathJax has to reset any LaTeX in question descriptions, which is annoying.
