### ISSUE TITLE
Message on leaving a question without submitting

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#255]
If set, the message says:

You haven't submitted all your answers on this page.
Proceed anyway?
                            modal.cancel     modal.ok

Instead of cancel, ok

See, for example

https://numbas-editor.mas.ncl.ac.uk/numbas-previews/exam-54-mas1241-cba-4-assessed/index.html

**Comment by christianp** [comment]
This was just an out-of-date version of our internal strings file.
