### ISSUE TITLE
Subscripts which are variables in JME

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#266]
$\simplify{x_5}$ displayed properly with subscript as expected, but  if v is a variable taking numeric values the $\simplify{x_{v}}$ displayed as x(a) where a is value of v. See https://numbas.mathcentre.ac.uk/question/9161/subscripts-in-jme/

Would expect it to be displayed with subscript the value of v.

**Comment by christianp** [comment]
No.Variable names don't work that way. If they did, we couldn't have variable names like `x_1`, because the `1` part would itself be variable.
I could add a pretend function like `sub(x,v)` which renders as `x_<whatever v is>`, but can't be evaluated.

**Comment by BillFoster** [comment]
We would need this for a linear algebra extension ( at least) - so I would welcome such a function as sub(x,v)

Sent from my iPhone

On 3 Aug 2015, at 09:14, Christian Perfect <notifications@github.com<mailto:notifications@github.com>> wrote:


No.Variable names don't work that way. If they did, we couldn't have variable names like x_1, because the 1 part would itself be variable.
I could add a pretend function like sub(x,v) which renders as x_<whatever v is>, but can't be evaluated.

-
