### ISSUE TITLE
Problem in editing a user-defined function

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#267]
I am trying to edit the function nw_algorithm in https://numbas.mathcentre.ac.uk/question/9377/minimum-cost-algorithm/

In particular to change the while statement to something like while(ct<=9).
However, if I attempt to edit this, everything freezes , chrome snaps and IE sometimes tells me that there is a long-running script interfering.

**Comment by christianp** [comment]
This is caused by an infinite loop. Javascript doesn't let me watch functions and stop them if they take too long.
I suppose you could turn off automatic regeneration of variables while editing the function, since they only get evaluated when used in a variable definition.

**Comment by christianp** [comment]
Can I close this?

**Comment by BillFoster** [comment]
Yes

Sent from my iPhone

On 2 Sep 2015, at 15:59, Christian Perfect <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I close this?

-
