### ISSUE TITLE
Show a sensible error message when uploading non-.exam file

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#274]
Trying to uploading a question or an exam gives the following error message (part of)

UnicodeDecodeError at /exam/upload/
'utf8' codec can't decode byte 0xb0 in position 11: invalid start byte
Request Method:	POST
Request URL:	https://numbas.mathcentre.ac.uk/exam/upload/
Django Version:	1.7.4
Exception Type:	UnicodeDecodeError
Exception Value:	
'utf8' codec can't decode byte 0xb0 in position 11: invalid start byte
Exception Location:	/opt/python/lib/python2.7/encodings/utf_8.py in decode, line 16
Python Executable:	/usr/bin/python
Python Version:	2.7.3
Python Path:	
['/opt/python/local/lib/python2.7/site-packages/pip-1.3.1-py2.7.egg',
 '/opt/python/lib/python2.7',
 '/opt/python/lib/python2.7/plat-linux2',
 '/opt/python/lib/python2.7/lib-tk',
 '/opt/python/lib/python2.7/lib-old',
 '/opt/python/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/opt/python/local/lib/python2.7/site-packages',
 '/opt/python/local/lib/python2.7/site-packages/PIL',
 '/srv/www/numbas.mathcentre.ac.uk/numbas_editor',
 '/srv/numbas/dist/bin']
Server time:	Tue, 27 Oct 2015 22:05:15 +0000
Unicode error hint

The string that could not be encoded/decoded was: ]�[G��J

**Comment by BillFoster** [comment]
All down to my mistake in trying to upload a scorm package rather than the source file!

**Comment by christianp** [comment]
There should be a more sensible error message, like "it looks like the file you uploaded is not a .exam source file", when you do this.
