### ISSUE TITLE
Making search better

### ISSUE THREAD

**Issue by christianp** [numbas/editor#277]
Some ideas we've had about finding questions in the database.

* Everyone has different syllabuses and categorisations
* A "level of ability" is not a universal concept, but people understand levels in terms of buckets - an English lecturer will go [GCSE, A-Level, BsC, ...], while a Scottish lecturer will go [Access, Intermediate, Higher, BsC, ...], and an American might go [K-12 (possibly through common core), college, university, ... ]
* The time things are taught differs by subject as well - a mathematician will be taught in year 1 what an engineer might only learn in year 3, and vice versa.

So it's complicated. A possible solution is a filtering and refining interface, where you narrow down what you want by adding constraints on level of ability, or topic, or subject. By the time you've done that, the matching set should be small enough that you can search by keyword or by eye.

The interface for someone searching for questions would look like a travel-booking interface, or amazon - lots of ways of narrowing down options on the side, and make sure to show how many matching items are outside the current range. 

The "level of ability" filter should first ask for a framework, and then add some landmarks on a scale. For example, if the user picks "English higher ed" as the framework, then it will mark [GCSE, A-Level, foundation, stage 1, 2, 3] on the scale. The user then picks a start and end point for the range of abilities they want to consider.

For people writing questions, we need to make sure they add all the necessary information! A single screen should take them through the process of defining all the necessary information. They should only need to do this once, but it won't necessarily be when they start the question. 

**Is this OK:** A question can only show up in the public database once it's had all the metadata added.

The user should be shown a list of their untagged questions on the homepage, as a queue to work through. "This is junk and I'll never tag it" should be an option.

**Comment by chrismgraham** [comment]
> Is this OK: A question can only show up in the public database once it's had all the metadata added.

I think so!

**Comment by BillFoster** [comment]
Must be careful that authors do not find it too wearisome to do this, but yes.

Sent from my iPad

On 30 Nov 2015, at 16:14, Chris Graham <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this OK: A question can only show up in the public database once it's had all the metadata added.

I think so!

-

**Comment by christianp** [comment]
This was what triggered v2!
