### ISSUE TITLE
Button to lock a variable value in the preview

### ISSUE THREAD

**Issue by christianp** [numbas/editor#282]
While debugging, it would be nice if you could keep a particular variable constant while you fiddle with others.
Locking a variable would mean that it, and any variables it uses, are not regenerated when a variable regeneration is triggered (either by pressing the "regenerate variables" button or by changing a definition).

Should editing the definition of a locked variable unlock it, or should the editing field be disabled?

**Comment by BillFoster** [comment]
Unlock before being able to change so editing field disabled.
