### ISSUE TITLE
If one or more questions in an exam aren't labelled "ready to use", show a warning before download

### ISSUE THREAD

**Issue by christianp** [numbas/editor#296]
If an exam contains one or more questions labelled with something other than "ready to use", then when a user tries to download a .zip of the exam, pop up a warning first.
This should prompt people to check questions before showing them to students, and mean that problems flagged up by colleagues on other people's questions don't go unnoticed.

There should be a "proceed anyway" button, of course.

**Comment by christianp** [comment]
You could do this by setting a class on the "Download" dropdown when there's a problem, maybe with a tooltip explaining what the problem is. The wrinkle here is that ideally it should update when the status of the questions in the exam changes, without a page reload. We're already polling every few seconds for recently changed and basket questions, so the relevant info could get chucked in with that response.

**Comment by gerlou** [comment]
Hi Christian, 

I'm starting to work on this issue.

**Comment by chrismgraham** [comment]
This seems to have been done some time ago.
