### ISSUE TITLE
Hidden function scripts in V2 editor

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#301]
If a question has a function script then the script is not displayed on first entering the question in the V2 editor. You have to click on the content area to see the script.

https://numbas-editor.mas.ncl.ac.uk/question/1496/william-s-copy-of-add-a-custom-ruleset/

**Comment by christianp** [comment]
This is a bug with the codemirror editor, linked to the bug that makes TinyMCE the wrong size sometimes.
