### ISSUE TITLE
Using back arrow after cancelling leave a project.

### ISSUE THREAD

**Issue by BillFoster** [numbas/editor#306]
If you click on leave a project then cancel this, on clicking the back arrow you are asked again if you want to leave. In contrast, this is not asked if you  click on the back arrow without first asking to leave.

**Comment by christianp** [comment]
What? Why would it ask you to confirm if you never asked to leave?

**Comment by BillFoster** [comment]
No, if you ask to leave a project then cancel then you cannot use the backarrow to go back to your list of projects without being asked the same question. To go back in this case you have to click on NUMBAS at top left.

**Comment by christianp** [comment]
That's how the back button is supposed to work.

**Comment by BillFoster** [comment]
OK I take your point, but it is not clear (least ways to me) how to go back to the home page for the user.

**Comment by christianp** [comment]
The following procedure starts and ends in the same place:

* On the project homepage, click "leave project"
* Click "cancel"
* Press the back button twice.

**Comment by BillFoster** [comment]
Why not a button saying back to home page or something similar?

**Comment by christianp** [comment]
There are lots of ways of getting to a project page, so it makes no sense to add links for each of them. The back button does what it should.
