### ISSUE TITLE
"Ignore and publish anyway" button on the publish checklist

### ISSUE THREAD

**Issue by christianp** [numbas/editor#320]
Sometimes I want to publish a question that doesn't have all the usual necessary bits, in particular advice. "How-to" questions to demonstrate techniques to question authors are the usual reason.

There should be an "ignore the checklist and publish anyway" button on the Access screen, when not all of the tasks are complete.

**Comment by christianp** [comment]
**To do this:**

* In [editor/static/js/editor.js](https://github.com/numbas/editor/blob/master/editor/static/js/editor.js#L311), add a property `ignored_publishing_criteria` to the `EditorItem` object.
* In [editor/templates/editoritem/edit.html](https://github.com/numbas/editor/blob/master/editor/templates/editoritem/edit.html#L304), add a button which sets the `ignored_publishing_criteria` property to true. Then, show the block with the publish button in it if either of `all_sections_completed` or `ignored_publishing_criteria` is true.

I want an explicit "ignore" button, rather than just duplicating the 'publish' button, to make the point that this isn't recommended behaviour.

**Comment by gerlou** [comment]
Hi Christian, 

I just wanted to let you know I'm interested in working on this issue. Thanks for the tips above.

**Comment by gerlou** [comment]
Just to clarify, do you want an "ignore" button at the top of the Access screen, so that when you click on the ignore button, it will show the block with the publish button and then, the user can click the publish button and publish their question? Or, do you want to have an "ignore" button which then shows the Publish block, and inside the Publish block, there would be two buttons, one "ignore and publish" button and one "publish" button?

**Comment by christianp** [comment]
Hi @gerlou,
I'd like a button in the "Publish" block, just beneath the list of tasks, which says "Ignore these tasks and publish". When you click that, the "Publish" button will appear.

**Comment by gerlou** [comment]
Hi Christian,

I finished the code but when I was testing, I found out that if the user clicks the ignore button, then goes back to the Settings tab, changes the License so all sections should be completed, and then changes it back to "none specified" so not all sections are completed again, then the Publish block with the publish button will still show up underneath the ignore button. I thought the Publish block shouldn't be there until I press the ignore button again. If I reload the page then it's fine, but if I switch between tabs after I press the ignore button the first time so I'm changing the value of all_sections_completed and ignored_publishing_criteria, then the Publish block will still show up underneath the Ignore button part. Do you know how I could reset the flag when the user leaves the current tab?

**Comment by christianp** [comment]
Open a pull request with your current code and I'll have a look.
