### ISSUE TITLE
Publishing an exam should try to publish all the questions as well.

### ISSUE THREAD

**Issue by christianp** [numbas/editor#323]
Amy found it too tedious to go through and publish each of her questions individually.
Here's a way of making it easier: when you publish an exam, try to publish all of the questions. If they satisfy the criteria (got a statement, licence, etc.) and you have edit access, publish them. List any questions which couldn't be published, with reasons, on the confirmation page.

**Comment by christianp** [comment]
If an exam uses a question which hasn't been published, should that prevent the exam from being published?

**Comment by christianp** [comment]
**To do this:**

* In [editor/views/editoritem.py](https://github.com/numbas/editor/blob/master/editor/views/editoritem.py#L487), modify the `PublishView` to check if the item being published is an exam (`item.item_type=='exam'`). If so, for each of the questions in the exam:
 * check it can be edited by the user.
 * check it satisfies the publishing criteria (this is done in javascript on the item editing pages at the moment - can we easily check all of the criteria from Python? And how do we ensure they don't get out of sync?)
 * If so, publish the question. If not, remember why, and [flash a message](https://docs.djangoproject.com/en/1.10/ref/contrib/messages/) listing the questions that couldn't be published.

**Comment by gerlou** [comment]
Hi Christian, 

I was working on this issue and I wasn't sure how to get the questions in the exam from the editoritem, if the type is exam. Inside editoritem.py, under the PublishView class, I have this: 

def post(self, request, *args, **kwargs):
        ei = self.get_object()
        if (ei.item_type == 'exam'):

So from object ei, how would I get the questions in the exam?

**Comment by gerlou** [comment]
I actually figured it out and I think I know how to do it now.

**Comment by christianp** [comment]
I'm sorry to do this, but now I've seen the code running, I don't think it's a good idea any more! 
I don't like the questions being published as an unannounced side-effect of publishing the exam. Maybe we should have "publish all the questions" as one of the pre-publication tasks before publishing an exam.

I also don't like reproducing the pre-publication tasks for questions inside the model, when they're also defined in JavaScript.

I'm going to close this. Thanks for trying, and I hope you learnt some more Python!
