### ISSUE TITLE
Replace question with a copy: house the copy in the current project?

### ISSUE THREAD

**Issue by chrismgraham** [numbas/editor#348]
When using the "replace this question with a copy" button, my (naive?) expectation was that it would be created in the current project (i.e. the one that the exam is in), rather than the question's original location. The motivation for creating a copy at this point seems most likely to be that the question needs to be customised for use on the exam.

**Comment by christianp** [comment]
Yep, that sounds like a bug.

**Comment by christianp** [comment]
To fix this: in [editor/static/js/exam/edit.js](https://github.com/numbas/editor/blob/master/editor/static/js/exam/edit.js#L449), change the request made in `replaceWithCopy` to specify the current exam's project. It looks like the [`CopyEditorItemForm`](https://github.com/numbas/editor/blob/master/editor/forms.py#L212) has a `project` field, that will take the PK of a project.
