### ISSUE TITLE
Success class when adding from basket inside the exam editor

### ISSUE THREAD

**Issue by chrismgraham** [numbas/editor#350]
When adding questions from the basket inside an exam, there is little indication that a question has been added successfully following a click. This could be a success class for the add icon (in the same way as the basket item turns green when clicked in the search view), or some other indication of which questions in the basket are already included in the exam.

**Comment by christianp** [comment]
This is a good idea.

To do this: 
* in [`editor/static/js/exam/edit.js`](https://github.com/numbas/editor/blob/master/editor/static/js/exam/edit.js#L426), add a computed observable `usedInExam` to the `Question` class, which returns true when a question with the same `id` is present in the exam's question list. (I'm not sure whether there's an explicit list of all the exam's questions at the moment - they're separated into question groups)
* in [`editor/templates/exam/edit.html`](https://github.com/numbas/editor/blob/master/editor/templates/exam/edit.html#L328), add a `css` binding to the `.glyphicon-plus` tag, to add the class `text-success` when `usedInExam` is true. ([docs about the css binding](http://knockoutjs.com/documentation/css-binding.html))

**Comment by narendravardi** [comment]
Hi @christianp,
I would like to work on this issue. Is there any one working on this?

**Comment by christianp** [comment]
@narendravardi thanks for offering. Nobody's working on this at the moment.

**Comment by narendravardi** [comment]
@christianp Thanks for letting me know. I am making a local installation of Numbas in order to make changes and test locally. Will keep you updated on the status.

**Comment by jastee07** [comment]
Is this still in progress or is it open?

**Comment by christianp** [comment]
@jastee07 I don't think anyone is currently taking this on.
