### ISSUE TITLE
Circular definition causes variable editing issue

### ISSUE THREAD

**Issue by chrismgraham** [numbas/editor#352]
If you construct a variable with a circular definition you quite rightly get a warning. However, if you then hit the spacebar, the variable preview empties, and the regenerate / add a variable buttons no longer function, even on correcting the variable definition. (It can be resolved by refreshing the page).

**Comment by christianp** [comment]
There's a "maximum call stack size exceeded" error, which implies that some knockout computed observables have circular references to each other somewhere along the line. I can't see exactly where it happens, but I can probably pin it down.
