### ISSUE TITLE
Trying to use a reserved name for a variable should show an error

### ISSUE THREAD

**Issue by christianp** [numbas/editor#353]
If you try to use a reserved name for a variable, for example `e`, a warning should be shown.

**Comment by christianp** [comment]
The constants are defined in [`Numbas.jme.constants`](https://github.com/numbas/Numbas/blob/master/runtime/scripts/jme.js#L39)

**Comment by gerlou** [comment]
Hi @christianp , 

If no one is working on this, I'd like to work on this issue. Thanks.

**Comment by gerlou** [comment]
I'm looking at the code for this issue and I'm not sure which files to start with. Could you give me some pointers on where to look? Thanks.

**Comment by gerlou** [comment]
Hi Christian, 

I just fixed this issue and made a pull request. Could you take a look at it? Thanks.

**Comment by christianp** [comment]
Thanks for fixing this, in #373.
In future, if you put the issue number in your commit message, your pull request will show up in the corresponding issue, and the issue will get closed automatically when I merge your pull request.
