### ISSUE TITLE
Uncaught TypeError shown in JS console when creating a variable and validation fails

### ISSUE THREAD

**Issue by extigy** [numbas/editor#362]
**Steps to reproduce:**
Create a new question.
Add a new variable and give it a name.
Choose Random number from a range as the data type
Set one of the numbers as something like "abcd"

**Result:**
![image](https://cloud.githubusercontent.com/assets/982548/25522464/e5715954-2bfa-11e7-98f6-b20739d03fae.png)

**Comments:**
I'm not sure this is totally related to the "value is not a number" problem I created. As far as I can tell it seems to be something to do with trimming the name of the variable instead.

**Comment by christianp** [comment]
Good catch!
`Variable.definition` was returning `undefined` when an error occurred. Later on, some code assumes the definition is always a string and tries to `trim` it.
I've changed `Variable.definition` to return an empty string when an error occurs. This doesn't change anything semantically: `Variable.definitionError` still gets set, so you can distinguish an empty definition from one with an error.
