### ISSUE TITLE
Show when a variable is used in the testing condition

### ISSUE THREAD

**Issue by christianp** [numbas/editor#369]
An icon or something in the variable list next to variables which are used in the variable testing condition would make the workings of a question much clearer.
At the moment, if the testing condition ensures a certain property holds, it can be quite confusing to work out why a question always seems to work!

**Comment by gerlou** [comment]
Hi Christian, 

I'd like to work on this issue. Thanks.

**Comment by christianp** [comment]
@gerlou OK - have a look in [`editor/templates/question/edit.html`](https://github.com/numbas/editor/blob/master/editor/templates/question/edit.html#L322), somewhere around the padlock icon for locked variables. We should show another icon when the variable is referred to in the variable testing condition. 
You'll want to use [`Numbas.jme.findvars`](http://numbas.github.io/Numbas/Numbas.jme.html#.findvars) to find the vairables used in the testing condition.

**Comment by gerlou** [comment]
Hi Christian, 

I just finished this issue and made a pull request. I used a flag icon to show that the variables were being used in the testing condition. Let me know if I should change it to something else. Thanks.
