### ISSUE TITLE
Searched users should be shown in alphabetical order 

### ISSUE THREAD

**Issue by christianp** [numbas/editor#370]
**To do this:** add `.order_by('first_name','last_name')` to the end of the `users = ` query in `find_users` in [`accounts/util.py`](https://github.com/numbas/editor/blob/master/accounts/util.py) so that the `User` objects are returned in order.

**Comment by gerlou** [comment]
Hi Christian, 

Could you describe in more detail about this issue and where I can search for users?

**Comment by christianp** [comment]
@gerlou I've added a description above.

**Comment by gerlou** [comment]
I changed the code but I'm not sure where to test it. I tried this link http://localhost:8080/admin/auth/user/ but it seems like it's always ordered by the username instead of the first and last name.
