### ISSUE TITLE
Warning in a gap's header if it's not included in the part prompt.

### ISSUE THREAD

**Issue by christianp** [numbas/editor#384]
This happens most often when you're deleting gaps from a part. If the gap isn't included in the prompt, there's no way of submitting it.
(This is allowed because some hacky questions use hidden gaps to store answers generated by other interactive elements)

The panel header for a gap should show a warning symbol if the gap isn't included in the prompt. The text should be clear that this isn't necessarily an error, but needs attention.

**Comment by extremelypenguin** [comment]
Hey! could you leave a tutorial on how to reproduce the bug as well as where the code is located? Thanks
