### ISSUE TITLE
Extensions in the user profile should be sorted alphabetically

### ISSUE THREAD

**Issue by christianp** [numbas/editor#387]
In `accounts/profile/<pk>/extensions`, the list of extensions should be sorted alphabetically. I think at the moment they're sorted by creation date, which isn't visible on the page.

**Comment by jastee07** [comment]
I'd like to give this a shot if that's alright

**Comment by christianp** [comment]
@jastee07 sure! Read [our page on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code), and make sure you get the editor running locally so you can test your code.
