### ISSUE TITLE
If you can't see a question used in an exam, you shouldn't be able to see an exam

### ISSUE THREAD

**Issue by christianp** [numbas/editor#397]
You can be granted access to an exam, but you might not also have access to all of its questions. In this case, a "forbidden" page should be shown explaining that the exam contains questions you haven't been given permission to see.

**Comment by MaanasArora** [comment]
Can I work on this issue?

**Comment by christianp** [comment]
Hi @MaanasArora, thanks for offering to help. No need to ask permission - if you send a pull request, I'll have a look at it.
Make sure you have a look at [our page on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/) first.

**Comment by Bhavya-Ahir** [comment]
Hey, this issue still open? Can I work on it?

**Comment by christianp** [comment]
@Bhavya-Ahir yes, it's still open. I'd be glad to receive a pull request fixing it.

**Comment by Bhavya-Ahir** [comment]
Hello,
I get this error when I tried installing all the requirements, I can't find a solution
Please help!

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\bhavya\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bhavya\\AppData\\Local\\Temp\\pip-install-017mxa_u\\borgbackup\\setup.py'"'"'; __file__='"'"'C:\\Users\\bhavya\\AppData\\Local\\Temp\\pip-install-017mxa_u\\borgbackup\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\bhavya\AppData\Local\Temp\pip-install-017mxa_u\borgbackup\pip-egg-info'
         cwd: C:\Users\bhavya\AppData\Local\Temp\pip-install-017mxa_u\borgbackup\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bhavya\AppData\Local\Temp\pip-install-017mxa_u\borgbackup\setup.py", line 188, in <module>
        raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))
    Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/borg, /opt/local, /opt/pkg)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by christianp** [comment]
@Bhavya-Ahir it looks like you don't have the OpenSSL development libraries installed. I don't use anaconda so I don't know what you need to do to get it installed, but hopefully that's a pointer in the right direction.

**Comment by christianp** [comment]
The "page not found" or "access forbidden" message needs to say why you can't see the exam.

**Comment by christianp** [comment]
... and that's already in! Whoops
