### ISSUE TITLE
Catch variable definitions of the form `x= ...`

### ISSUE THREAD

**Issue by christianp** [numbas/editor#398]
A few people copied out definitions like `x0 = random(-9..9)` from the docs, not realising that the `x0 = ` was just to show which variable the definition relates to.
The editor should catch definitions of the form `<name> = <expr>` and say something like "you don't need `<name> = ` at the start of your definition."

**Comment by bhaveshpoddar94** [comment]
First Timer here. Can I take a look at the issue?

**Comment by christianp** [comment]
Hi @bhaveshpoddar94, thanks for offering. Submit a pull request once you've got something.
