### ISSUE TITLE
Variable name input for an adaptive marking replacement should be a dropdown

### ISSUE THREAD

**Issue by christianp** [numbas/editor#430]
Currently, it's a text input. This means you have to type out the name rather than pick it, and allows you to type an invalid name.
It should be a dropdown instead, listing all question variables alphabetically.

**Comment by strudra** [comment]
I could tackle this one. Still open, right?

**Comment by christianp** [comment]
@strudra yes, it's still open. Thanks for offering. If you haven't already, please have a look at [our guidelines on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code).

**Comment by syn228** [comment]
Is this still open? Could I try tackling it?

**Comment by akshett** [comment]
Is this still open? I wanted to attempt this.

**Comment by christianp** [comment]
@akshett yep

**Comment by akshett** [comment]
I created a pull request for this fix. I referred to this issue in the header. Please let me know if you have any feedback/suggestions.
