### ISSUE TITLE
'Mark Student Answer' scripts cannot end in a comment

### ISSUE THREAD

**Issue by JoshuaCapel** [numbas/editor#433]
I discovered some of my old questions were breaking and tracked down the bug to fact I had left some commented out code on final line of the **'Mark Student Answer'** script in a few of my question parts.

Trying to run the question with a comment on the final line lead to the error: **SyntaxError: missing ) in parenthetical**.

To recreate this just add this code to final line of any of the **'Mark student's answer (active)'** scripts.
```
// This will break
```
You don't even need to test run the question to see this error. The **'Marking algorithm'** for the part (just above **'Scripts'**) shows the same error in the section titled **'Test that the marking algorithm works'**.

It's worth noting that if you add a new blank line after the comment then it works fine, e.g.
```
// This won't break

```

Ending a script in a comment is obviously not really something I need, so my fix is to just avoid this behavior in the future.

**Comment by christianp** [comment]
Oops! Thanks for reporting this.

Fixed by numbas/Numbas@6b16afc
