### ISSUE TITLE
display of sets in variable preview is sometimes too long

### ISSUE THREAD

**Issue by christianp** [numbas/editor#439]
I have a feeling I've recently done the opposite of what I'm about to propose: when the string rendering of a set is too long, the preview should instead say something like "set of N items", similar to how lists are displayed.

**Comment by JoshuaCapel** [comment]
I think I have resolved this with pull request: https://github.com/numbas/editor/pull/443

**Comment by christianp** [comment]
Thanks! I've merged it in.
For future reference: it makes my life easier if you create a separate branch for each pull request. That way, if you have more than one pull request open at once, I can merge them separately.

**Comment by JoshuaCapel** [comment]
Okay, I will make sure to branch in the future.
