### ISSUE TITLE
Question group names should not be editable in non-editable mode

### ISSUE THREAD

**Issue by christianp** [numbas/editor#449]
The inputs for question group names in the exam editor remain editable when the exam is not editable by the current user. They shouldn't.

**Comment by docoleman** [comment]
I can take this one. I found the spot, I believe I have the fix too.

https://github.com/numbas/editor/blob/288b700584e4e3c230cdf41bf1d808f20b0a99ab/editor/templates/exam/edit.html#L89

I also dropped the X from the group section AND removed the add group button at the bottom of the form. I should be able to have a PR by tomorrow.
