### ISSUE TITLE
Chrome Preview frame height

### ISSUE THREAD

**Issue by Tandethsquire** [numbas/editor#451]
In Google Chrome (v66.0.3359.139 - not sure if Chrome-specific or version-specific), the "Test Run" of a question opens as a frame with 300px height, rather than filling the main area. Adding "height: 100%" to the specification for main in preview.css fixes the problem. No such problem in Firefox.

**Comment by christianp** [comment]
I can't reproduce in Chrome 74, but someone else reported in Safari. `height: 100%` does indeed fix it. 
Thanks for reporting this!

**Comment by christianp** [comment]
Fixed in 095c3fc6109795866d2d6f430c45658b64d838ef. Sorry, forgot to mention this issue in the commit message
