### ISSUE TITLE
Some way of expanding displayed values of large lists and dictionaries

### ISSUE THREAD

**Issue by christianp** [numbas/editor#493]
At the moment, the values of lists and dictionaries aren't shown directly, just text of the form "List of N items".

We can't always display the full JME representation, because it might fill the screen. Maybe a truncated string could be shown, and clicking on it would launch a pop-up with the full string.

**Comment by moisesjsanchez** [comment]
Hello first time contributor here. Would it be okay if I can take a try at this?

**Comment by christianp** [comment]
@moisesjsanchez thanks for offering to help! Please have a look at [our guide on contributing code to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code).

Let me know when you've got something I can look at, or if you need help.

**Comment by sandeepmukh** [comment]
Hi, could I help with this issue? I'm also a first-time contributor.

**Comment by sandeepmukh** [comment]
Hi could I also take a look at this? I'm a first-time contributor as well.
