### ISSUE TITLE
Broken help link

### ISSUE THREAD

**Issue by ugoertz** [numbas/editor#533]
In the Extensions tab of a user's profile (file accounts/templates/profile/extensions.html), the help link points to `{{HELP_URL}}extensions.html` but it should point to `{{HELP_URL}}extensions/index.html`.

Thanks for the great work!

**Comment by sudiptog81** [comment]
True, Reproducible on the editor hosted at https://numbas.mathcentre.ac.uk which redirects to https://docs.numbas.org.uk/en/latest/extensions.html instead of https://docs.numbas.org.uk/en/latest/extensions/. I am fixing this and sending a PR 😄
