### ISSUE TITLE
Problem with uploading themes

### ISSUE THREAD

**Issue by ugoertz** [numbas/editor#535]
Clicking the "Upload a new theme" button in the user's profile triggers a server error.

It is caused by the reference to the url named `profile_themes` which does not exist:
 https://github.com/numbas/editor/blob/f57fde543a2fd1d92a14306bf9ce3e4dd458f2d0/editor/templates/theme/create.html#L31
It should be `theme_list_profile` (or that one should be renamed). Currently, `profile_themes` is used in other theme-related templates and in the file editor/views/theme.py.

After changing this, I get the theme upload form. However, uploading a zip file using this form also gave an error (AttributeError, 'Theme' object has no attribute 'ensure_extracted_path_exists', at editor/forms.py, line 530). I did not look further into this. It might have been caused since my zip file only had the inherit.txt file(?)

**Comment by ugoertz** [comment]
A few further notes: (I am not sure I am getting the full picture, though ...)

* It seems that `templates/theme/edit.html` (which has a `profile_themes` reference) is not used.
* Despite the AttributeError, the theme is actually uploaded and can apparently be used, so in a local instance I think it should be enough to fix the `profile_themes` references (and ignore the error upon uploading) in order to be able to use custom themes.

As for the cause of the AttributeError:
For one thing, the Theme class does in fact not have a method `ensure_extracted_path_exists`. Probably the one from the `Extension` class should just be copied over, or the method could be moved to `EditablePackageMixin`. (However, some of this is currently taken care of in the `Theme.save` method so a few changes might be required; in fact, `Theme.save`has a TODO note pointing in this vry direction.)

In addition, there is some confusion whether we want to *create* or *upload* a theme. In the code, both options are present (more or less). In the UI, as far as I can see, upload is the only option offered to the user. However, the `Upload a new theme` button links to /theme/new, i.e., to creating a theme. Therefore the wrong form is used, and the `ensure_extracted_path_exists` is triggered. If it succeeded, the README.md file would be (over-)written, something that should not happen for uploaded themes.

Going directly to /theme/upload/ (a URL which is defined in editor/urls.py, but not linked to anywhere, as far as I can see) fails because the template `theme/upload.html` is missing.

**Comment by christianp** [comment]
Thanks for looking into this. In my rush to finish things before going on paternity leave, it seems I left the theme editor in an unfinished state. I think I've tidied it all up now.
