### ISSUE TITLE
Link to documentation: Lock this part

### ISSUE THREAD

**Issue by ugoertz** [numbas/editor#543]
In

https://github.com/numbas/editor/blob/c2ef3a5fbc681c29d315b4bd1267d3ce3eee2334/editor/templates/question/edit_part.html#L522

the link should point to https://docs.numbas.org.uk/en/latest/question/explore.html#term-lock-this-part
Also, should it be "Lock this part?" (rather than "Locks")?

**Comment by christianp** [comment]
Thanks for spotting this, @ugoertz!
