### ISSUE TITLE
Link to documentation: custom functions for a question.

### ISSUE THREAD

**Issue by ugoertz** [numbas/editor#548]
The anchor functions-rulesets doesn't seem to exist on that page:

https://github.com/numbas/editor/blob/9c724cfe71db4b73aff4fb7c4f5ebd16619f2f40/editor/templates/question/edit.html#L692

Maybe it should be https://docs.numbas.org.uk/en/latest/question/reference.html#functions (or https://docs.numbas.org.uk/en/latest/question/reference.html#rulesets ?).

**Comment by christianp** [comment]
Thanks for reporting these, @ugoertz. I've taken a more systematic approach and I think I've found all the broken links.
