### ISSUE TITLE
Show dimensions of multi-dimensional arrays

### ISSUE THREAD

**Issue by christianp** [numbas/editor#556]
At the moment, if I have a 3×3 list of lists, the variable preview just says "List of 3 items". I'd like it to say something like "Nested 3×3 list".

**Comment by do159hu** [comment]
Hi, I might be able to do this task. Can you give me some more information? I dont have an overview in this project.

**Comment by vallabhtiwari** [comment]
Hi @christianp is this issue still open? I would like to work on it. Could you give some more information on how to generate the preview?

**Comment by christianp** [comment]
@vallabhtiwari Sorry, this was resolved by @MaanasArora in #752, and I forgot to close the issue. 
Thanks for offering to help! You might like to try #676. Look at [the instructions on setting up a development environment](https://docs.numbas.org.uk/en/latest/development/installation.html), if you haven't already.

**Comment by christianp** [comment]
Whoops, I was wrong! #752 dealt with matrices and vectors, but not lists.

To demonstrate this problem: create a question and add a variable with definition `repeat(repeat(1),3),4)`. 
The variable values preview will show "List of 4 items". I'd like it to say "Nested 4×3 list". 

The relevant code is in [`editor/static/js/editor.js`](https://github.com/MaanasArora/editor/blob/58b861f6690867e159a1d245dcc625b697968307/editor/static/js/editor.js#L1860).

**Comment by Keyboardguy** [comment]
Hello - I have tried to solve this issue, and have made a pull request. This is my first time contributing to open source though, so please feel free to give feedback.
