### ISSUE TITLE
"show score feedback icon" and "show correct answer on reveal" fields show up twice for choose one from a list part

### ISSUE THREAD

**Issue by christianp** [numbas/editor#573]

**Comment by Blargian** [comment]
Hi, I'm new to opensource and would like to help out. Could I work on this?

**Comment by christianp** [comment]
@Blargian thanks for offering! Yes, please have a go. Please have a look at [our guidelines on contributing code to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code) first.
