### ISSUE TITLE
More informative "Forbidden" error

### ISSUE THREAD

**Issue by YannickNeyt** [numbas/editor#579]
I started working on a Numbas project that less tech savvy people started, but I'm constantly getting "Forbidden" errors for exams containing at least one "non access" question.

The error is very vague and it's hard to find out who's causing the problem.

It's also kinda counterintuitive that they can give me access to an exam, but I don't get acces to the questions in it.

**Comment by christianp** [comment]
Yes, I'm aware of this, and I think I'll switch back to being able to view exams even if they include some questions you can't see.

**Comment by christianp** [comment]
As of 2a09beb160944072c4, the default behaviour is now not to require access to all questions in order to see an exam.

**Comment by YannickNeyt** [comment]
Thanks, that really helps!
