### ISSUE TITLE
Matrix won't accept expression entries

### ISSUE THREAD

**Issue by mittkkoo** [numbas/editor#586]
I want to define a variable of type matrix, containing JME expressions. But this fails:

`matrix([expression("cos(delta)")],[expression("i*sin(delta)/n")])`

The error message says: 

> Error evaluating variable matrix_name: No definition of 'matrix' of correct type found.

Am I missing something or this is not possible?

**Comment by christianp** [comment]
The `matrix` data type can only represent matrices of real numbers. I have an open issue at numbas/Numbas#531 about making the vector and matrix types a bit more generic, but I don't know how that'll happen yet.

What do you want to do with this matrix? Is it just for display, or as an answer to a part, or do you need to do arithmetic with it?
