### ISSUE TITLE
Add ability to create multiple variables at once (or duplicate variables)

### ISSUE THREAD

**Issue by dualspiral** [numbas/editor#595]
Right now, I'm trying to set up a complicated matrix equation that has a lot of variables that generate random numbers in a given range. Right now, for each variable, I have to:

* Click "Add a variable"
* Give it a new name (for me, it's usually some prefix followed by an incrementing number)
* Paste a copied JME statement into the value box

When you have 20 variables to set up, this is a laboreous task. It would be nice to be able to be able to "batch create" variables like this so I just have to input the required information once and it'll create the multiple variables for me. Alternatively (maybe as well?), it would be nice to be able to duplicate a variable.

(I assume that this is a change on the editor side, so I've put the issue here - apologies if it's meant to go in the main numbas repo!)

**Comment by christianp** [comment]
I think you might want to create a list. For example, this creates a list of 20 numbers, each between 1 and 10:

```
repeat(random(1..10), 20)
```

This produces a 3 by 3 matrix with random values:

```
matrix( repeat( repeat( random(1..10), 3 ), 3 ) )
```

Can you give some more detail on how these variables will be used?

**Comment by dualspiral** [comment]
The intention itself is to create a matrix that I can display to students such that I can get them to write Python scripts to encode them in NumPy, manipulate them and then provide the answer that NUMBAS can validate. My intention was to try to get JME to solve a set of linear equations based on the random numbers and validate the answers the students gave, who will have done it in Python. However, the more I'm reading into JME, the more I feel like might be pushing it a bit far.

To be fair, I don't need to use random numbers for this question as the objective is to be able to perform a task in Python and this is a formative assessment. The code is not going to change based on input matrix (though part of the task is defining the matrix and randomising a matrix would force writing the input over and over again, which would at least enforce _that_ part of the course). I just thought it would be interesting to give it a go to see if it'd work out. I don't think it will without doing some magic with the mark-code extension, so I'll likely just create a few static questions instead.

Back on topic: using a list with randomly generated integers here is something I didn't realise I could do - so that's handy to know. However, I do think there is still some merit to what I'm asking for: in cases where something like multiple matrices for a question, it makes sense to assign them to different variables rather than creating a list of matrices - I know that's how I'd prefer to see it. I'd like to be able to at least duplicate a variable, even if my original request is based on incomplete knowledge of the system.

**Comment by christianp** [comment]
That's absolutely possible. The linear algebra extension has a few routines to make working with systems of equation easier. A trick that's always handy is to work backwards: randomly pick the solution, then generate a problem with that solution.

We have quite a few questions on solving systems of equations scattered around the place, but none that are both simple and public. I've made a new example in the "how-tos" project which creates a system of three equations in three unknowns and asks you to solve it: https://numbas.mathcentre.ac.uk/question/87303/generate-a-system-of-linear-equations-to-solve/

I can see where you're coming from with duplicating variables, but I think if you're doing that more than a couple of times you really should be using lists. It means it's easier to make a change, and you can use `map` to do calculations over all the values at once.

Did you know you can give several variable names in the "variable name" field, separated by commas, and they'll be matched up with the corresponding entries in whatever list you produce in the "definition" field? For example, if you put `x,y,z` in "Name", and `[1,2,3]` in "Definition", then that's equivalent to defining three separate variables `x=1`, `y=2`, `z=3`.

**Comment by dualspiral** [comment]
Huh, I didn't think about working backwards from a solution, I'll give that a go, and thank you for the example. Part of this, I admit, is due to relative inexperience with NUMBAS and a compressed time frame to get things working, and while the docs have been helpful there is no subsitution for trying things, of course. I've gotten to grips with it fairly quickly, I just found that the lack of duplication of variables was odd when being able to make a copy of questions, exams, parts, gaps etc. and felt it was something that was missing in my use case. 

I can see your points as to why you'd be reluctant to add a feature - indeed it's not what you'd want to do most of the time. Useful to know for future, thanks. I'll take this all on board.

**Comment by christianp** [comment]
Would you like a video call some time to talk about what you'd like to do?

**Comment by dualspiral** [comment]
Ah, sorry, I closed Github for the rest of the day. 

I got what I wanted to do done, but I'm open to the idea to having a chat at some point just to get a better feel of what NUMBAS can do for me. I'll send you an e-mail.
