### ISSUE TITLE
Show ticks and crosses for positive and negative feedback in the marking algorithm preview

### ISSUE THREAD

**Issue by christianp** [numbas/editor#630]
In the "marking algorithm" tab of the part editor, you can enter an answer and see the feedback produced. Each feedback item should have a tick or cross next to it as appropriate, like in the real exam interface.

**Comment by nikitakor7** [comment]
Hey @christianp can I solve this ?

**Comment by christianp** [comment]
@nikitakor7 thanks for offering to help! Please set up a development environment for the editor, following the instructions at https://docs.numbas.org.uk/en/latest/server-installation/index.html.

The relevant files to edit are [`editor/templates/question/edit_part.html`](https://github.com/numbas/editor/blob/master/editor/templates/question/edit_part.html#L282) and [`editor/static/js/question/edit.js`](https://github.com/numbas/editor/blob/master/editor/static/js/question/edit.js#L3704). You'll have to [replicate the logic from the Numbas runtime](https://github.com/numbas/Numbas/blob/master/runtime/scripts/part.js#L1558), to describe each feedback item as positive, negative, invalid or neutral.

Let me know if you need any help!

**Comment by sonam42** [comment]
Hi, @christianp can I try to work on this issue? I have opened the Numbas editor and have seen that it is still not done if I am not mistaken.

**Comment by christianp** [comment]
@sonam42 thanks for offering to help! Please look at [our guidance on contributing to Numbas](https://www.numbas.org.uk/contributing-to-numbas/#contributing-code).

**Comment by christianp** [comment]
@sonam42 great! Have you made a start? If you need any help, let me know.

**Comment by sonam42** [comment]
Thanks for offering help. So far I have just checked the code that's all. But if I need any help I'll let you know.

**Comment by klong124** [comment]
I wasn't sure if this is being worked on, so I was hoping to take a crack at it too.  I'm running into some issues installing the Numbas editor on Windows (I'm using Ubuntu on Windows).  When I try running first_setup.py it says that I don't have the module 'numbasobject'.

**Comment by sonam42** [comment]
Hi, this weekend I'm hoping to finally send solution for this issue.

**Comment by klong124** [comment]
Sounds good.

**Comment by sonam42** [comment]
I wanted to finally send a solution but when I "updated my installation" it isn't working. I can load the page through http://localhost:8000  and also log in but when I click on the button that creates the exam / question, this shows up on my screen. 
![image (3)](https://user-images.githubusercontent.com/87281984/142730124-24812802-9f23-43d0-9238-911ae9c1bb88.png)

and this after I click OK, so I just want to know if I make some mistake somewhere or if this is a new issue.  

![image (4)](https://user-images.githubusercontent.com/87281984/142730142-f8973b3f-adfc-4ee9-9b92-ae8fa86b601f.png)

**Comment by christianp** [comment]
@sonam42 had you made changes to the javascript? A syntax error could cause it to fail to load. Have you looked at the developer console? (press F12)

**Comment by sonam42** [comment]
I even tried to clone the repositary again so no changes in JS but it does't work. 
Right now the error looks like this and it shows up immediately:

![image](https://user-images.githubusercontent.com/87281984/142896165-908d7994-51cc-4dce-898c-e7eb04d1675d.png)

![image](https://user-images.githubusercontent.com/87281984/142896601-e6c4eebb-d500-4919-b30c-a873d763ab25.png)

**Comment by sonam42** [comment]
Ok so I've cloned the repositary once again and for some reason it is wokring now
