### ISSUE TITLE
content areas show "click to edit" when disabled

### ISSUE THREAD

**Issue by christianp** [numbas/editor#644]
For example, the statement of a question, when you have viewing but not editing access.

**Comment by anshitabaid** [comment]
I would like to take this up

**Comment by christianp** [comment]
@anshitabaid thanks! The code to create the "click to edit" text is in [editor/static/js/editor.js](https://github.com/numbas/editor/blob/master/editor/static/js/editor.js#L1684). You should add something to check `element.hasAttribute('disabled')`, and not create the text if it is disabled.
