### ISSUE TITLE
Show a warning when a custom constant's value field is invalid

### ISSUE THREAD

**Issue by christianp** [numbas/editor#656]

**Comment by anshitabaid** [comment]
I would like to take this up. 
However, I'm confused about which custom constant is being referred to here. Could you please clarify?
![image](https://user-images.githubusercontent.com/34227502/151167447-a64b545c-9315-4a2e-bc6e-d96a8d7f6073.png)
Is it this?

**Comment by christianp** [comment]
@anshitabaid thanks for offering to help! This is about the "Custom constants" field, in the "Extensions & scripts" tab of the question editor. There's [a section in the documentation about it](https://docs.numbas.org.uk/en/latest/question/reference.html#constants).

For each custom constant, you must give a name, value, and a LaTeX string. If you type an invalid expression in the value field, such as `f(`, I'd like it to show a warning underneath. 

The "correct answer" field in the marking settings for a mathematical expression part has this warning, so you could copy that:

![image](https://user-images.githubusercontent.com/19513/151442129-029faae2-7d24-4070-bf71-f9b55ea13c0f.png)

The code for that is at https://github.com/numbas/editor/blob/master/editor/templates/question/part_types/jme.html#L9

**Comment by anshitabaid** [comment]
Thanks @christianp for this. However, it appears that this feature is already implemented. Or please correct me if I'm wrong.

![image](https://user-images.githubusercontent.com/34227502/151658757-eaddfdcf-e401-4415-bbb7-0a529b9b468b.png)

**Comment by christianp** [comment]
Oh, so it is! Sorry for wasting your time.
