### ISSUE TITLE
Make the preview header look nicer

### ISSUE THREAD

**Issue by christianp** [numbas/editor#657]
When you test run a question or exam, it's shown in a page with a banner across the top, showing links to edit, download or share the item.
At the moment, it doesn't have much styling:

![Screenshot 2022-01-10 at 08-46-51 CLP's Christmas Adventure - preview - clppc Numbas](https://user-images.githubusercontent.com/19513/148738829-007b492d-d05b-499e-b57d-852edd44c7a1.png)

I'd like it to look a little bit nicer. The page doesn't load the bootstrap styles used by the rest of the site; maybe it should. 

* It should look OK in a small portrait screen, and not take up too much space.
* I'm not very happy with the "Share" button at the moment - it pops up a `<code>` tag showing the URL, which it would ideally copy to the clipboard. 
* The header starts with "PREVIEW of ..." - is that necessary?

**Comment by sarthak0699** [comment]
Hello, I would like to take up this task. Could you also give some pointers on how exactly you want the header to look like, as OK is a bit ambiguous .

**Comment by christianp** [comment]
@sarthak0699 thanks for offering to help. I don't really have anything in mind, I just think it's not very attractive at the moment!

**Comment by Maheshwaran17** [comment]
@christianp I am working on this. i will share the image of preview banner once completed.

**Comment by Maheshwaran17** [comment]
Hi @christianp , Can you pls let me know if the below changes looks fine, If yes, i will then create a pull request. Please let me know if incase of any suggestions.

![image](https://user-images.githubusercontent.com/67360549/167169185-08bf6d72-3949-47fd-816e-3a08108dafa2.png)

**Comment by Maheshwaran17** [comment]
Hi @christianp , Thank you for the reply.

I have made the below changes and attached the images below for your reference.

1. Updated the text to 16px
2. For copying the URL, i used navigator.clipboard.writeText(<Value to be copied>);
3. Removed "Q:" before the question name.
4. The links on the right are now underlined.

Please let me know if you are happy with this look or let me know if in case of any corrections. I will submit the pull request based on your comment. Thanks in advance! 

![image](https://user-images.githubusercontent.com/67360549/167768382-d7600ac9-d7ee-43e8-90d7-b382faf17497.png)

**Comment by christianp** [comment]
That looks better, thanks. It's still not great for accessibility for the URL to disappear automatically. Apart from that, it all looks good!
