### ISSUE TITLE
Tags are not saved

### ISSUE THREAD

**Issue by zaript** [numbas/editor#693]
To reproduce:
Add a tag in Settings of any question and close the tab.

What I expect to see:
Tag is present on reopening the question.

What I see:
Tags field is empty.

**Comment by christianp** [comment]
I can create tags, so maybe it's something about the particular tags you tried to add?
Can you tell me what tags you added?

**Comment by zaript** [comment]
After playing with it, I realised that the tag entry field works differently from the name and description fields -- it does not autosave, but needs an Enter press to create the tag. My bad.
