### ISSUE TITLE
rest api usage

### ISSUE THREAD

**Issue by cli-ish** [numbas/editor#709]
Hello,

we are currently installing a numbas editor instance. The problem is that the LTI tool needs the api endpoints under /api for selection.
The exact configuration was here https://lti.xxx.tld/editorlinks.

Now we tried to adjust the settings.py file, there we added the entry editor_rest_api to INSTALLED_APPS and restarted. But the api is still not available. (see https://github.com/numbas/editor/blob/master/numbas/urls.py#L20-L27 )
We also did not found anything in the logs, no errors or anything.

Is there another option which needs to be set?
It should look like this: https://numbas.mathcentre.ac.uk/api/ but our installation throws 404

we used the master branches so we should be up to date.

**Comment by christianp** [comment]
Great!

I'll close it and make a new issue.
