### ISSUE TITLE
Match questions with answers does not show questions or answers on marking matrix

### ISSUE THREAD

**Issue by aarchiba** [numbas/editor#717]
The marking matrix entry makes invisible the questions and the answers, so you can't actually see which answer and which question each row and column correspond to. This makes entering the correct answers highly error prone. Why not simply show the questions and answers as row and column labels, as the actual question does?

**Comment by christianp** [comment]
Because it's not simple! I agree it would be nice to have the labels shown in cases where they're short, but the text for choices and answers could be arbitrarily long, which would make the table even harder to use than it already is.

I'll have another look at this later.

**Comment by aarchiba** [comment]
Wouldn't such long labels also make the question itself very difficult to use? Why is the marking matrix more difficult to render with long labels than the question itself?
