### ISSUE TITLE
media query css breaks editor

### ISSUE THREAD

**Issue by ugonj** [numbas/editor#719]
Including a media query in the css preamble of a question makes that question inaccessible. More specifically, I can continue editing and previewing the question but once I navigate away from it and try to edit it again, I get this dialog box:

```
TypeError: Unable to process binding "text: function(){return Editor.makeCSSMoreSpecific(preamble.css(),'#previewModal ') }"
Message: rule.style is undefined
```
and the error in the browser page is:
```
Unable to process binding "text: function(){return Editor.makeCSSMoreSpecific(preamble.css(),'#previewModal ') }"
Message: rule.style is undefined
```
To reproduce:

1. Create a question;
2. Navigate to "Extensions and Scripts/preamble"
3. In the css textbox enter `@media screen{  div {display: block;}}`
4. Navigate away from the question
5. Try to edit the question again.

**Comment by christianp** [comment]
Thanks for reporting this! I've made a fix in the development branch, which will hopefully go on the public site in the next couple of weeks.
