### ISSUE TITLE
No persistent indicator of whether changes have been saved.

### ISSUE THREAD

**Issue by aarchiba** [numbas/editor#731]
if you leave a page before the changes have been saved, the changes can fail to ever be recorded. It is hard to tell whether this is happening, because there is no way to tell whether the current state of the page is what is stored on the server. A "saving" message appears very briefly while saving is actually happening, but there is no persistent indication, so if you miss it you can wait forever for the saving to happen.

I have lost work in the editor, and I believe it was this.

**Comment by christianp** [comment]
Good point. we should add something.

**Comment by christianp** [comment]
Now looks like this:
![Screenshot 2022-11-10 at 15-56-06 Case-sensitive JME part answer display - CLPtop Numbas](https://user-images.githubusercontent.com/19513/201143387-a239e21b-70c3-4f65-ad8e-6009679bc52b.png)
