### ISSUE TITLE
Access restriction to editor despite using LTI-Provider (which requires exams to be public to see them)? 

### ISSUE THREAD

**Issue by bjoseru** [numbas/editor#738]
This is similar but different to numbas/Numbas#637 

Questions and exams on a university hosted editor need to be marked "public" for them to appear in the LTI provider. As the editor server can in theory be accessed by students being examined (for their weekly homework), it is desirable to keep the questions private. Currently, even a public user (not logged in) can see all public questions in the editor.

I am aware that I can keep questions/projects private and then download upload a SCORM package into the LTI provider, keeping much of its features. But I'd like to also keep the convenience of authoring and modifying questions in the editor and simply selecting an exam from the list in the LTI provider.

Is there a privacy setting I haven't found yet, or a more convenient workaround than the one described? Such as somehow turning off access for non-authenticated users completely?

**Comment by christianp** [comment]
There isn't a way of doing that at the moment. 
There was an issue about adding OAuth authentication, which would allow this, but I was only thinking about updating exam packages for existing resources at the time and solved it by including a token with each downloaded package: #546.

What I have in mind is:
* from the Numbas LTI tool, you click a link to authorise your account on the editor to see your content, through OAuth.
* then when you create a new resource in the LTI tool, your OAuth credentials are used to fetch a list of your content, maybe a list of recently-viewed items and a search box.

This is quite low down the priority list, though.

**Comment by bjoseru** [comment]
OK, thanks for the clarification and perspective. Not using OAuth here at the moment, unfortunately. We'll likely go with IP filtering and another second level authentication wrapper as a workaround for now then. That seems like the easiest though not ideal fix.
