### ISSUE TITLE
Exam level edit access setting is not saved

### ISSUE THREAD

**Issue by zaript** [numbas/editor#763]
Issue and a way to reproduce:

As shown in the screenshot, I am attempting to give an edit access to the exam. Editor displays "Saved" message. However, if I close the tab and navigate to exam again, the access setting is not present.

![SCR-20230320-npfp-2](https://user-images.githubusercontent.com/77082/226386971-f3761eda-1d81-482a-a94a-589ea122de5c.png)

The view access seems to save fine.

**Comment by christianp** [comment]
Thanks for reporting this! Fixed by c09454c6f0675f43a7145813f92dbdb776a03968
