### ISSUE TITLE
No horizontal scrolling for output in the "Testing section"

### ISSUE THREAD

**Issue by charlesmorisset** [numbas/editor#764]
This is a cosmetic issue rather than functional. In the "Testing" tab of the development of a code question, there is no horizontal scrolling when the outputs exceeds the expected width. Example below with using the "print(locals())" statement. 

<img width="1442" alt="Screenshot 2023-04-27 at 12 34 56" src="https://user-images.githubusercontent.com/33661754/234850624-85e6f36e-3cbf-4cf6-85d1-aabd6987ea32.png">

As you can see, the grey box following "Your code produced this output:" is too wide, and cannot be scrolled horizontally (tested on Safari 16.0). 

The behaviour is correct in the actual "run" of the question: 

<img width="1227" alt="Screenshot 2023-04-27 at 12 39 14" src="https://user-images.githubusercontent.com/33661754/234851247-8e768507-fd38-4f55-b367-304da2d7f7af.png">

The box is now with the correct width and can be scrolled horizontally.

**Comment by christianp** [comment]
Ah, thanks for reporting this.
