### ISSUE TITLE
'Reveal answers to all questions' dropdown hidden when menu mode is selected

### ISSUE THREAD

**Issue by chrismgraham** [numbas/editor#766]
The dropdown  _Reveal answers to all questions_ is only visible when sequential navigation mode is selected. I noticed that the LTI tool still uses the value for that setting, or at least it does in the table of settings on the LTI dashboard. So to update requires changing from menu mode to sequential, updating the setting, then going back to menu mode.

**Comment by christianp** [comment]
When numbas/Numbas#917 is implemented, the setting will also make a functional difference.
