### ISSUE TITLE
Adaptive marking: replacing variable with gap answer freezes the editor on "Loading"

### ISSUE THREAD

**Issue by ugonj** [numbas/editor#791]
When adaptive marking is set in a question so that a variable should be replaced with the value of a gap answer, the question can no longer be reloaded. Instead the screen remains on "Loading". The error occurs in edit.js, line 3649.

Here is an example: https://numbas.mathcentre.ac.uk/question/share/view/78bfc2da-5a90-4820-a76a-273836c0091d

**Comment by christianp** [comment]
Thanks for reporting this!
